[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas 报告
gas_reports = ["*"]
gas_reports_ignore = []

# 测试配置
fuzz_runs = 256
verbosity = 4

# 网络配置
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
local = "http://localhost:8545"

# 编译器设置
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

# 覆盖率设置
[profile.default.coverage]
report = true
report_lcov = true
report_html = true
report_summary = true

# 调试设置
[profile.default.debug]
fuzz = { runs = 100 }
invariant = { runs = 100 }

# 生产环境配置
[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true
gas_reports = ["*"]

# 测试环境配置
[profile.test]
optimizer = false
optimizer_runs = 0
via_ir = false
gas_reports = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options